server:
  port: 16080  servlet:    encoding:      charset: UTF-8      enabled: false      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    name: dmt
    url: jdbc:mysql://localhost:3306/dmt?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: dmtuser
    password: Dmt1218-
  devtools:
     restart:
        enabled: true
  cache:
    type: redis
    redis:
      time-to-live: 3600000 #缓存超时时间ms
      cache-null-values: false #是否缓存空值
  redis:
    host: localhost
    database: 2
    port: 6379
    password: 
    timeout: 10000
    jedis:
      pool:
        min-idle: 0
        max-active: 10
        max-idle: 10
        max-wait: 200

file-upload:  location: C:\\html\\UploadFiles\\

jwt:
  secret: a1g2y47dg3dj59fjhhsd7cnewy73j
  expiration: 28800
  tokenheader: x-auth-token
  