server:
  port: 8090  servlet:    encoding:      charset: UTF-8      enabled: false      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    name: dmt
    url: jdbc:mysql://localhost:3306/information_schema?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  devtools:
     restart:
        enabled: true
        
logging:
  config: classpath:logback.xml

generator:
  tableSchema: ts
  baseFolder: C:/work/sts/generator/generated
  sqlFolder: sql/
  pageFolder: html/src/views/
  apiFolder: html/src/api/
  mappingFolder: src/main/resources/mapping/
  javaSourceFolder: src/main/java/
  mapperPkg: me.too.ts.core.dao
  modelPkg: me.too.ts.core.model
  servicePkg: me.too.ts.core.service
  serviceImplPkg: me.too.ts.core.service.impl
  controllerPkg: me.too.ts.web.controller